# Generated by Django 4.2.21 on 2025-06-05 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(choices=[('RN', 'Registered Nurse'), ('LPN', 'Licensed Practical Nurse'), ('CNS', 'Clinical Nurse Specialist'), ('NP', 'Nurse Practitioner'), ('CRNA', 'Certified Registered Nurse Anesthetist'), ('CNM', 'Certified Nurse Midwife')], max_length=10)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiry', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('hire_date', models.DateField()),
                ('employment_status', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('TEMP', 'Temporary'), ('INACTIVE', 'Inactive')], default='FULL_TIME', max_length=20)),
                ('shift_preference', models.CharField(choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift'), ('EVENING', 'Evening Shift'), ('ROTATING', 'Rotating Shifts'), ('ON_CALL', 'On Call')], default='DAY', max_length=20)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('certifications', models.JSONField(default=list, help_text='List of additional certifications')),
                ('skills', models.JSONField(default=list, help_text='List of nursing skills')),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('last_training_date', models.DateField(blank=True, null=True)),
                ('performance_rating', models.DecimalField(blank=True, decimal_places=1, help_text='Rating out of 5.0', max_digits=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('can_supervise', models.BooleanField(default=False)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_nurses', to='shared.nurse')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nurses',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
