# Generated by Django 4.2.21 on 2025-06-05 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0002_nurse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('drug_code', models.CharField(max_length=50, unique=True)),
                ('drug_type', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('LIQUID', 'Liquid/Syrup'), ('INJECTION', 'Injection'), ('CREAM', 'Cream/Ointment'), ('INHALER', 'Inhaler'), ('DROPS', 'Drops'), ('PATCH', 'Patch')], max_length=20)),
                ('category', models.CharField(choices=[('ANTIBIOTIC', 'Antibiotic'), ('PAINKILLER', 'Pain Killer'), ('ANTIVIRAL', 'Antiviral'), ('ANTIFUNGAL', 'Antifungal'), ('CARDIAC', 'Cardiac Medicine'), ('DIABETES', 'Diabetes Medicine'), ('HYPERTENSION', 'Hypertension Medicine'), ('RESPIRATORY', 'Respiratory Medicine'), ('MENTAL_HEALTH', 'Mental Health Medicine'), ('VITAMIN', 'Vitamin/Supplement'), ('OTHER', 'Other')], max_length=20)),
                ('strength', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('side_effects', models.TextField()),
                ('contraindications', models.TextField()),
                ('storage_conditions', models.CharField(max_length=200)),
                ('requires_prescription', models.BooleanField(default=True)),
                ('is_controlled_substance', models.BooleanField(default=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medications',
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pharmacy_type', models.CharField(choices=[('HOSPITAL', 'Hospital Pharmacy'), ('RETAIL', 'Retail Pharmacy'), ('CLINICAL', 'Clinical Pharmacy'), ('ONLINE', 'Online Pharmacy')], max_length=20)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('operating_hours', models.CharField(max_length=100)),
                ('is_24_hours', models.BooleanField(default=False)),
                ('delivery_available', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pharmacies',
                'db_table': 'pharmacies',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_number', models.CharField(max_length=50, unique=True)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('ONCE_DAILY', 'Once Daily'), ('TWICE_DAILY', 'Twice Daily'), ('THREE_TIMES', 'Three Times Daily'), ('FOUR_TIMES', 'Four Times Daily'), ('AS_NEEDED', 'As Needed'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=20)),
                ('duration_days', models.PositiveIntegerField()),
                ('quantity_prescribed', models.PositiveIntegerField()),
                ('refills_allowed', models.PositiveIntegerField(default=0)),
                ('refills_used', models.PositiveIntegerField(default=0)),
                ('instructions', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FILLED', 'Filled'), ('DISPENSED', 'Dispensed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('prescribed_date', models.DateTimeField(auto_now_add=True)),
                ('filled_date', models.DateTimeField(blank=True, null=True)),
                ('dispensed_date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateField()),
                ('pharmacist_notes', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='shared.doctor')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='pharmacy.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='shared.patient')),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='pharmacy.pharmacy')),
            ],
            options={
                'db_table': 'prescriptions',
            },
        ),
        migrations.CreateModel(
            name='PharmacyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('minimum_stock_level', models.PositiveIntegerField(default=10)),
                ('batch_number', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.CharField(max_length=200)),
                ('last_restocked', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='pharmacy.medication')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='pharmacy.pharmacy')),
            ],
            options={
                'db_table': 'pharmacy_inventory',
                'unique_together': {('pharmacy', 'medication', 'batch_number')},
            },
        ),
    ]
